Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,9 +17,9 @@ jobs:
         with:
           ref: ${{ github.ref }}  # Checkout the branch that triggered the workflow (push or PR)
 
-      - name: Fail delibariately
-        run:
-          exit 1
+      # - name: Fail delibariately
+      #   run:
+      #     exit 1
       - name: Show current branch name
         run: 
           echo ${{ github.ref }}
@@ -29,7 +29,7 @@ jobs:
     steps:
       - name: Show current branch name
         run: 
-          echo ${{ github.ref }}    
+          exit 1 # echo ${{ github.ref }}    
   third_job:
     runs-on: ubuntu-latest
     needs: [checkout, second_job]
