Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,14 +16,12 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.ref }}  # Checkout the branch that triggered the workflow (push or PR)
-      
+
+      - name: Fail delibariately
+        run:
+          echo "Failing deliberately"
+          exit 1
       - name: Show current branch name
         run: 
-          exit 1
-  deploy:
-    runs-on: ubuntu-latest
-    needs: checkout
-    if: failure()  # Only runs if the 'checkout' job succeeds
-    steps:
-      - name: Deploy to server
-        run: echo "Deploying to server..."
+          echo {{ github.ref }}
+  
