Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,16 +17,22 @@ jobs:
         with:
           ref: ${{ github.ref }}  # Checkout the branch that triggered the workflow (push or PR)
 
-      - name: Fail delibariately
-        run:
-          exit 1
+      # - name: Fail delibariately
+      #   run:
+      #     exit 1
       - name: Show current branch name
         run: 
           echo ${{ github.ref }}
 
   second_job:
     runs-on: ubuntu-latest
-    needs: checkout
+    steps:
+      - name: Show current branch name
+        run: 
+          echo ${{ github.ref }}    
+  third_job:
+    runs-on: ubuntu-latest
+    needs: [checkout, second_job]
     if: success()
     steps:
       - name: Show current branch name
