Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,26 +17,26 @@ jobs:
         with:
           ref: ${{ github.ref }}  # Checkout the branch that triggered the workflow (push or PR)
 
-      - name: Fail delibariately
-        run:
-          exit 1
+      # - name: Fail delibariately
+      #   run:
+      #     exit 1
       - name: Show current branch name
         run: 
           echo ${{ github.ref }}
 
-  second_job:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Show current branch name
-        run: 
-          echo ${{ github.ref }}    
-  third_job:
-    runs-on: ubuntu-latest
-    needs: [checkout, second_job]
-    # if: ${{ failure('checkout') && success('second_job') }}
-    if: success()
-    steps:
-      - name: Show current branch name
-        run: 
-          echo ${{ github.ref }}    
+  # second_job:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Show current branch name
+  #       run: 
+  # #         echo ${{ github.ref }}    
+  # third_job:
+  #   runs-on: ubuntu-latest
+  #   needs: [checkout, second_job]
+  #   # if: ${{ failure('checkout') && success('second_job') }}
+  #   if: success()
+  #   steps:
+  #     - name: Show current branch name
+  #       run: 
+  #         echo ${{ github.ref }}    
   
