Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,3 +20,21 @@ jobs:
       - name: Show current branch name
         run: 
           echo ${{ github.ref }}
+  deploy:
+    runs-on: ubuntu-latest
+    needs: checkout
+    if: success()  # Only runs if the 'checkout' job succeeds
+
+    steps:
+      - name: Deploy to server
+        run: echo "Deploying to server..."
+
+  fail_if_critical:
+    runs-on: ubuntu-latest
+    needs: checkout
+    if: success()  # This job only runs if the test job success
+    steps:
+      - name: Critical Failure Handler
+        run: |
+          echo "Test job failed, halting deployment."
+          exit 1
